### ISSUE TITLE
#FFF circle color picker selected state on white background

### ISSUE THREAD

**Issue by proevilz** [casesandberg/react-color#530]
If you use a CirclePicker color of #fff (white) and put it on a white background, the box shadow color is white and the default 'white' circle that appears is also... white. This leaves you with basically an invisible color picker.

I would propose that if the color is #fff then make the box shadow color #000 by default and change the selected circle that appears to include a #000 colored border on it.

**Comment by proevilz** [comment]
I also tried copying the ones from this repo out the `src` folder and get the same error...

**Comment by proevilz** [comment]
**Update:** If I remove line 32 & 34 it works as expected.... However, it seems I cannot change the box-shadow since you're using it to set the actual color of the circle.

**Comment by casesandberg** [comment]
Hmm, maybe we need to do something custom for the white swatch. Maybe we should add a slight border to it or something?

**Comment by andrew-pyle** [comment]
@casesandberg Thinking about this issue for Hacktoberfest 2019. 

I don't know if there is a solution for this problem—any of the color swatches would disappear on a background which is identical to their own color, just like the white one.

Whatever is done for white would have to be done on all circle swatches to be effective

![image](https://user-images.githubusercontent.com/25519964/66707726-0670f500-ed0b-11e9-88db-736481077a7d.png)
![image](https://user-images.githubusercontent.com/25519964/66707733-1983c500-ed0b-11e9-9253-d7a77847209a.png)

**Comment by andrew-pyle** [comment]
I'll submit a pull request which implements the following OPTION for solving the problem of color swatches disappearing on identical background:
- Swatches always have grey border. Makes color swatch visible on same color background.
- Add grey ring inside selected color ring. Makes selection visible on same color background.
- Always use grey shadow shadow on selected, rather than the color of the swatch. Matches grey border.

**Comment by Cvrane** [comment]
> I'll submit a pull request which implements the following OPTION for solving the problem of color swatches disappearing on identical background:
> 
> * Swatches always have grey border. Makes color swatch visible on same color background.
> * Add grey ring inside selected color ring. Makes selection visible on same color background.
> * Always use grey shadow shadow on selected, rather than the color of the swatch. Matches grey border.
> * Adds a borderColor prop & default color

Hey, @andrew-pyle was this issue solved? I'm running into the same problem where I'm using a white swatch and it disappears into the background!

**Comment by andrew-pyle** [comment]
@Cvrane I am not aware of any more progress than stalled PR #649 above.

@casesandberg Any ideas besides adding the grey border?

Maybe we can detect the background color and add a grey border only in the case that they match?

**Comment by Cvrane** [comment]
> @Cvrane I am not aware of any more progress than stalled PR #649 above.
> 
> @casesandberg Any ideas besides adding the grey border?
> 
> Maybe we can detect the background color and add a grey border only in the case that they match?

Thank you so much for replying and offering to help! I looked into adding a black border just to the white swatch but it just  seems to not work. Any suggestions are appreciated!

**Comment by andrew-pyle** [comment]
@Cvrane have you looked at the approach used in PR #649?

**Comment by jsheets2-chwy** [comment]
A combination of CSS and a dynamic `white-selected` className is working for us for now:
```css
  .circle-picker {
    div[title="#ffffff"] {
      border: 1px solid #999;
    }
    &.white-selected {
      div[title="#ffffff"] {
        box-shadow: #999 0 0 0 3px inset !important;
        border: none;

        &:focus {
          box-shadow: #999 0 0 0 3px inset, 0 0 5px #999 !important;
        }
      }
    }
  }
```
```jsx
<CirclePicker
   className={chosenColor === '#ffffff' ? 'white-selected' : ''}
   color={chosenColor}
/>
```
<img width="232" alt="image" src="https://user-images.githubusercontent.com/80271332/135333387-f3358a94-14fb-480d-a480-2a5fabcdc7c0.png">

**Comment by jeffsheets** [comment]
A combination of CSS and a dynamic `white-selected` className is working for us for now:
```css
  .circle-picker {
    div[title="#ffffff"] {
      border: 1px solid #999;
    }
    &.white-selected {
      div[title="#ffffff"] {
        box-shadow: #999 0 0 0 3px inset !important;
        border: none;

        &:focus {
          box-shadow: #999 0 0 0 3px inset, 0 0 5px #999 !important;
        }
      }
    }
  }
```
```jsx
<CirclePicker
   className={chosenColor === '#ffffff' ? 'white-selected' : ''}
   color={chosenColor}
/>
```
<img width="232" alt="image" src="https://user-images.githubusercontent.com/80271332/135333387-f3358a94-14fb-480d-a480-2a5fabcdc7c0.png">
