### ISSUE TITLE
Doesn't work in Next.js

### ISSUE THREAD

**Issue by utiq** [casesandberg/react-color#743]
I can setup the component in Next.js, it renders fine but I'm not able to select any color. Did anyone had the same issue?

**Comment by herrfugbaum** [comment]
You need to pass a handler to onChange or onChangeComplete, save the result in state and pass the color back via the color prop. This is not Next.js specific, see #741 and the [examples](http://casesandberg.github.io/react-color/#examples)

I have changed the second example for myself to work with Next.js and their CSS module support, hope it helps:
(Note: I did not lift state up for use for the parent component yet)

**ColorPicker.js**
```jsx
import { useState } from "react";
import { SketchPicker } from "react-color";

import styles from "./ColorPicker.module.css";

export const ColorPicker = () => {
  const [state, setState] = useState({
    displayColorPicker: false,
    color: {
      r: '241',
      g: '112',
      b: '19',
      a: '1',
    },
  });

  const handleClick = () => {
    setState({...state, displayColorPicker: !state.displayColorPicker });
  };

  const handleClose = () => {
    setState({...state, displayColorPicker: false });
  };

  const handleChange = (color) => {
    setState({...state, color: color.rgb });
  };

  return (
    <div>
      <div className={ styles.swatch } onClick={ handleClick }>
        <div className={ styles.color } style={{background: `rgba(${ state.color.r }, ${ state.color.g }, ${ state.color.b }, ${ state.color.a })`}}/>
      </div>
      { state.displayColorPicker ?
        <div className={ styles.popover }>
          <div className={ styles.cover } onClick={ handleClose }/>
          <SketchPicker color={ state.color } onChange={ handleChange } />
        </div> : null
      }
    </div>
  )
}
```

**ColorPicker.module.css**
```css
.color {
  width: 36px;
  height: 14px;
  border-radius: 2px;
}

.swatch {
  padding: 5px;
  background: #fff;
  border-radius: 1px;
  box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1);
  display: inline-block;
  cursor: pointer;
}

.popover {
  position: absolute;
  z-index: 2;
}

.cover {
  position: fixed;
  top: 0px;
  right: 0px;
  bottom: 0px;
  left: 0px;
}
```
